### ISSUE TITLE
Xcode 6.3.2 can't show menu 

### ISSUE THREAD

**Issue by ilklatte** [Draveness/ATProperty#2]
![snip20150606_3](https://cloud.githubusercontent.com/assets/3444766/8018424/ae3a56bc-0c4d-11e5-897d-d0fc0e8503cb.png)

how to solve this problem? 
Thank you!

**Comment by draveness** [comment]
I don't know why, maybe you should reinstall this plugin.

**Comment by ilklatte** [comment]
I have reinstall this plugin. The shortcut works ok. But the menu still can't show. I want to configure the code style. 
Menu doesn't show, it doesn't matter. 
Thank you all the same!

**Comment by draveness** [comment]
My Xcode version is 6.3.2. I am updating Xcode now, and I will try to figure it out.

**Comment by ilklatte** [comment]
Thank you！
